java_binary(
    name= "helloworld",
#    srcs= ["HelloWorld.java"],
    srcs = glob(["*.java"]),
    main_class = "com.company.helloworld.HelloWorld",
    deps = [
        "//src/main/java/com/company/greeter:greeter"
    ]
)